css-layout-classes created - William Zhang
williamzhang73/c0124-code-solutions pull request #36
Opened 2024-02-08 18:09 UTC by williamzhang73

![layout](https://github.com/williamzhang73/c0124-code-solutions/assets/151261985/7ab5efa8-ee8b-4733-84bf-3a370133be70)

2024-02-08 18:13 UTC, shawnkost requested changes
Few changes here William! Let me know if you have any questions

2024-02-08 18:13 UTC, shawnkost commented on css-layout-classes/index.html
> +            <div class="column-one-second"><img src="images/link.png" /></div>
This `column-one-second` class is unnecessary, and causing your images not to display propertly.

The `img` should just be in the `column-two-third` directly

2024-02-08 18:13 UTC, shawnkost commented on css-layout-classes/index.html
> +          </div>
All 3 of these columns should be the same. They should all be a `column-one-third`

2024-02-08 18:13 UTC, shawnkost commented on css-layout-classes/index.html
> +          </div>
These columns are different sizes. The one with the text should be taking up 2/3rds whereas the image will be the one-third

2024-02-08 18:13 UTC, shawnkost commented on css-layout-classes/index.html
> +          </div>
These columns are different sizes. The one with the text should be taking up 2/3rds whereas the image will be the one-third

2024-02-08 18:13 UTC, shawnkost commented on css-layout-classes/styles.css
> +
Missing selectors for the rest of your columns. Every single one of your `column` classes should have a selector with a `flex-basis` or `width` applied

2024-02-08 18:49 UTC, williamzhang73 commented
![lay](https://github.com/williamzhang73/c0124-code-solutions/assets/151261985/1f58ac94-cab5-4efa-916b-c8f43c9f6330)

2024-02-09 17:53 UTC, shawnkost approved these changes
👍🏻

2024-02-09 18:55 UTC, merged